//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie_Details
    {
        public int Movie_Id { get; set; }
        public string Movie_Name { get; set; }
        public System.DateTime Movie_Release_Date { get; set; }
        public int Movie_Colections { get; set; }
        public string Movie_Poster { get; set; }
    }
}
