//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account_details
    {
        public int Account_Id { get; set; }
        public int Deposits { get; set; }
        public int Account_No { get; set; }
        public int User_Id { get; set; }
    
        public virtual BANK_DETAILS BANK_DETAILS { get; set; }
    }
}
