//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctors_H
    {
        public int Doctor_Id { get; set; }
        public string Doctor_name { get; set; }
        public string Designation { get; set; }
        public string Degree { get; set; }
        public string Dealing_with { get; set; }
        public int max_consultation { get; set; }
        public int Password { get; set; }
        public int Contact_No { get; set; }
    }
}
