//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class H_Doctor
    {
        public int Doctor_Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Phone_Number { get; set; }
        public string Qualification { get; set; }
        public string Gender { get; set; }
        public string Department { get; set; }
        public int No_of_patient_assigned { get; set; }
        public int Max_Consultation { get; set; }
    }
}
