//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class H_Patient
    {
        public int Patient_No { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public int Age { get; set; }
        public System.DateTime Date { get; set; }
        public string Contact_no { get; set; }
        public string Room_no { get; set; }
        public string Department { get; set; }
        public Nullable<int> Doctor_Id { get; set; }
        public string Doctor_Name { get; set; }
        public string Patient_Type { get; set; }
        public string Symptoms { get; set; }
        public string Medicines { get; set; }
        public string Tests { get; set; }
    }
}
