//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Harshita_Movies
    {
        public int Movie_Id { get; set; }
        public string Movie_Name { get; set; }
        public string Poster { get; set; }
        public int Release_Year { get; set; }
        public int BoxOffice_Collection { get; set; }
    }
}
