//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Harshita_Patient_details
    {
        public int Patient_Id { get; set; }
        public string Patient_Name { get; set; }
        public string City { get; set; }
        public string Gender { get; set; }
        public string Diagnosis { get; set; }
        public Nullable<int> Room_No { get; set; }
        public int Doctor_Id { get; set; }
    }
}
