//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Harshita_Movie_booking
    {
        public int Id { get; set; }
        public string Movie_Name { get; set; }
        public Nullable<int> Theatre_Id { get; set; }
        public string Show_Timing { get; set; }
    
        public virtual Harshita_Theatres Harshita_Theatres { get; set; }
    }
}
