//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkDemo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class masterEntities : DbContext
    {
        public masterEntities()
            : base("name=masterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account_details> Account_details { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<BANK_DETAILS> BANK_DETAILS { get; set; }
        public virtual DbSet<City_srk_vam> City_srk_vam { get; set; }
        public virtual DbSet<Credit_details> Credit_details { get; set; }
        public virtual DbSet<Doctor_details> Doctor_details { get; set; }
        public virtual DbSet<Doctor_srk> Doctor_srk { get; set; }
        public virtual DbSet<Doctors_H> Doctors_H { get; set; }
        public virtual DbSet<File_Harika> File_Harika { get; set; }
        public virtual DbSet<H_Billdetails> H_Billdetails { get; set; }
        public virtual DbSet<H_Doctor> H_Doctor { get; set; }
        public virtual DbSet<H_Patient> H_Patient { get; set; }
        public virtual DbSet<Harshita_Movie_booking> Harshita_Movie_booking { get; set; }
        public virtual DbSet<Harshita_Movies> Harshita_Movies { get; set; }
        public virtual DbSet<Harshita_Patient_details> Harshita_Patient_details { get; set; }
        public virtual DbSet<Harshita_Theatres> Harshita_Theatres { get; set; }
        public virtual DbSet<movie_nithin> movie_nithin { get; set; }
        public virtual DbSet<MovieShow_harika> MovieShow_harika { get; set; }
        public virtual DbSet<MovieTheatre_Harika> MovieTheatre_Harika { get; set; }
        public virtual DbSet<nithin_movy> nithin_movies { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<Patient_H> Patient_H { get; set; }
        public virtual DbSet<PlaceTheatre_Harika> PlaceTheatre_Harika { get; set; }
        public virtual DbSet<prabhucityTable> prabhucityTables { get; set; }
        public virtual DbSet<prabhufolderlistTable> prabhufolderlistTables { get; set; }
        public virtual DbSet<prabhumovieTable> prabhumovieTables { get; set; }
        public virtual DbSet<prabhutheatreTable> prabhutheatreTables { get; set; }
        public virtual DbSet<prabhuTimeTable> prabhuTimeTables { get; set; }
        public virtual DbSet<Room_Details> Room_Details { get; set; }
        public virtual DbSet<rp_Doctor> rp_Doctor { get; set; }
        public virtual DbSet<Table> Tables { get; set; }
        public virtual DbSet<TableDoctors_Harika> TableDoctors_Harika { get; set; }
        public virtual DbSet<TablePatients_Harika> TablePatients_Harika { get; set; }
        public virtual DbSet<Theatre_svn> Theatre_svn { get; set; }
        public virtual DbSet<Timing_svn> Timing_svn { get; set; }
        public virtual DbSet<Movies_Harika> Movies_Harika { get; set; }
        public virtual DbSet<MSreplication_options> MSreplication_options { get; set; }
        public virtual DbSet<Patient_details> Patient_details { get; set; }
        public virtual DbSet<rp_Patient> rp_Patient { get; set; }
        public virtual DbSet<spt_fallback_db> spt_fallback_db { get; set; }
        public virtual DbSet<spt_fallback_dev> spt_fallback_dev { get; set; }
        public virtual DbSet<spt_fallback_usg> spt_fallback_usg { get; set; }
        public virtual DbSet<spt_monitor> spt_monitor { get; set; }
        public virtual DbSet<spt_values> spt_values { get; set; }
    
        public virtual int sp_MScleanupmergepublisher()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MScleanupmergepublisher");
        }
    
        public virtual int sp_MSrepl_startup()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MSrepl_startup");
        }
    }
}
