//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieShow_harika
    {
        public int Id { get; set; }
        public string MovieName { get; set; }
        public string MorningShow { get; set; }
        public string NoonShow { get; set; }
        public string FirstShow { get; set; }
    }
}
