//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class movie_nithin
    {
        public int MovieId { get; set; }
        public string Moviename { get; set; }
        public string Poster { get; set; }
        public System.DateTime ReleaseDate { get; set; }
        public int BoxOfficeCollection { get; set; }
    }
}
