//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movies_Harika
    {
        public int MovieId { get; set; }
        public string MovieName { get; set; }
        public System.DateTime ReleaseDate { get; set; }
        public string Poster { get; set; }
        public int BoxOffice { get; set; }
        public Nullable<int> Year { get; set; }
    }
}
