//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class nithin_movy
    {
        public int MId { get; set; }
        public string Mname { get; set; }
        public System.DateTime Mrelease { get; set; }
        public decimal Mcoll { get; set; }
    }
}
