//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public int Id { get; set; }
        public string Patient_name { get; set; }
        public string Gender { get; set; }
        public int Age { get; set; }
        public int Address { get; set; }
        public string Contact_Number { get; set; }
        public string Occupation { get; set; }
        public string Problem_Type { get; set; }
        public System.DateTime Last_Vist { get; set; }
    }
}
