//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class prabhuTimeTable
    {
        public int Time_id { get; set; }
        public string show_timings { get; set; }
        public int theatre_id { get; set; }
    
        public virtual prabhutheatreTable prabhutheatreTable { get; set; }
    }
}
