//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class prabhutheatreTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public prabhutheatreTable()
        {
            this.prabhuTimeTables = new HashSet<prabhuTimeTable>();
        }
    
        public int theatre_id { get; set; }
        public string theatre_name { get; set; }
        public int city_id { get; set; }
    
        public virtual prabhucityTable prabhucityTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prabhuTimeTable> prabhuTimeTables { get; set; }
    }
}
