//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class prabhumovieTable
    {
        public int Movie_id { get; set; }
        public string movie_name { get; set; }
        public System.DateTimeOffset Movie_release_date { get; set; }
        public string movie_poster { get; set; }
        public string movie_collections { get; set; }
    }
}
