//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class prabhufolderlistTable
    {
        public int folder_Id { get; set; }
        public string item_name { get; set; }
        public int item_size { get; set; }
        public string item_directory_name { get; set; }
        public string item_full_name { get; set; }
        public string item_extension { get; set; }
    }
}
