//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class rp_Patient
    {
        public int P_Id { get; set; }
        public string Patient_Name { get; set; }
        public string Gender { get; set; }
        public string City { get; set; }
        public Nullable<int> Room_No { get; set; }
        public string Symptom { get; set; }
        public Nullable<int> D_Id { get; set; }
    
        public virtual rp_Doctor rp_Doctor { get; set; }
    }
}
