//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TablePatients_Harika
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string city { get; set; }
        public string gender { get; set; }
        public string diagnosis { get; set; }
        public int did { get; set; }
    
        public virtual TableDoctors_Harika TableDoctors_Harika { get; set; }
    }
}
