//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timing_svn
    {
        public int Theatre_Id { get; set; }
        public string Timings { get; set; }
        public int Timings_Id { get; set; }
    
        public virtual Theatre_svn Theatre_svn { get; set; }
    }
}
