//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Vamsi_Gamidi_DBEntities : DbContext
    {
        public Vamsi_Gamidi_DBEntities()
            : base("name=Vamsi_Gamidi_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Franchise> Franchises { get; set; }
        public virtual DbSet<IPL> IPLs { get; set; }
        public virtual DbSet<Movie_Details> Movie_Details { get; set; }
        public virtual DbSet<Table> Tables { get; set; }
        public virtual DbSet<Theatre> Theatres { get; set; }
    }
}
