INSERT INTO [dbo].[IPL] ([Id], [Name], [Age], [Role], [Franchise]) VALUES (1, N'Vamsi Gamidi', 20, N'Batsman', N'MI')
INSERT INTO [dbo].[IPL] ([Id], [Name], [Age], [Role], [Franchise]) VALUES (2, N'Rohit', 30, N'Batsman', N'MI')
INSERT INTO [dbo].[IPL] ([Id], [Name], [Age], [Role], [Franchise]) VALUES (3, N'Yuvraj', 35, N'Allrounder', N'SRH')
INSERT INTO [dbo].[IPL] ([Id], [Name], [Age], [Role], [Franchise]) VALUES (4, N'Bhuvi', 26, N'Bowler', N'SRH')
INSERT INTO [dbo].[IPL] ([Id], [Name], [Age], [Role], [Franchise]) VALUES (5, N'Kane Williamson', 28, N'Batsman', N'SRH')
INSERT INTO [dbo].[IPL] ([Id], [Name], [Age], [Role], [Franchise]) VALUES (6, N'Virat', 28, N'Batsman', N'RCB')
INSERT INTO [dbo].[IPL] ([Id], [Name], [Age], [Role], [Franchise]) VALUES (7, N'Stokes', 27, N'Allrounder', N'RPS')
INSERT INTO [dbo].[IPL] ([Id], [Name], [Age], [Role], [Franchise]) VALUES (8, N'Quinton DeKock', 25, N'Wicket Keeper', N'DD')
INSERT INTO [dbo].[IPL] ([Id], [Name], [Age], [Role], [Franchise]) VALUES (9, N'Dale Steyn', 36, N'Bowler', N'SRH')
INSERT INTO [dbo].[IPL] ([Id], [Name], [Age], [Role], [Franchise]) VALUES (10, N'Pollard', 32, N'Allrounder', N'MI')
INSERT INTO [dbo].[IPL] ([Id], [Name], [Age], [Role], [Franchise]) VALUES (11, N'Gambhir', 35, N'Batsman', N'KKR')
INSERT INTO [dbo].[IPL] ([Id], [Name], [Age], [Role], [Franchise]) VALUES (12, N'ABD', 31, N'Batsman', N'RCB')
INSERT INTO [dbo].[IPL] ([Id], [Name], [Age], [Role], [Franchise]) VALUES (13, N'Manish Pandey', 27, N'Batsman', N'KKR')
INSERT INTO [dbo].[IPL] ([Id], [Name], [Age], [Role], [Franchise]) VALUES (14, N'MS Dhoni', 36, N'Wicket Keeper', N'RPS')
INSERT INTO [dbo].[IPL] ([Id], [Name], [Age], [Role], [Franchise]) VALUES (15, N'JP Duminy', 32, N'Allrounder', N'DD')
INSERT INTO [dbo].[IPL] ([Id], [Name], [Age], [Role], [Franchise]) VALUES (16, N'Shreyas Iyer', 21, N'Batsman', N'DD')
INSERT INTO [dbo].[IPL] ([Id], [Name], [Age], [Role], [Franchise]) VALUES (17, N'Dinesh Karthik', 32, N'Wicket Keeper', N'DD')
INSERT INTO [dbo].[IPL] ([Id], [Name], [Age], [Role], [Franchise]) VALUES (18, N'Kuldeep Yadav', 20, N'Bowler', N'KKR')
INSERT INTO [dbo].[IPL] ([Id], [Name], [Age], [Role], [Franchise]) VALUES (19, N'Ben Stokes', 27, N'Allrounder', N'RPS')
INSERT INTO [dbo].[IPL] ([Id], [Name], [Age], [Role], [Franchise]) VALUES (20, N'Ajinkya Rahane', 29, N'Batsman', N'RR')
INSERT INTO [dbo].[IPL] ([Id], [Name], [Age], [Role], [Franchise]) VALUES (21, N'Alex Hales', 26, N'Batsman', N'MI')
